# RBAC role for lambda-post-signup
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-post-signup
  namespace: default
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create"]
  - apiGroups: ["core"]
    resources: ["secrets"]
    verbs: ["get", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-post-signup
  namespace: default
subjects:
  - kind: User
    name: lambda-post-signup
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: lambda-post-signup
  apiGroup: rbac.authorization.k8s.io
